### ISSUE TITLE
The new update destroyed my games performance

### ISSUE THREAD

**Issue by vlad1m** [AllTheMods/Gravitas2#342]
Before the update my game run at stable 100 fps,after the update it barely reaches 50 fps,and mostly sits at ~35 fps,and its not related to the distant horizon mod,since i usually play without it.

**Comment by cdecompilador** [comment]
I just tried it out today and performance seems to be horrible only at night, weird, at daytime I get 144+ fps, at night I'm stuck at 20-30, I've tried disabling features from a couple mods like, dynamic lights, true darkness, distant horizons, etc, ... but still nothing. Seems to be a fully cpu issue since enabling/disabling shaders doesn't affect the fps at all so it should be easy to pin-point but its in my opinion a **critical bug** since it makes the modpack unplayable in low end pcs at night.

**Comment by thevortex** [comment]
you can update the TFC Aurora mod,  this is the likely source, using newest version things should improve

**Comment by vlad1m** [comment]
Yep,just tested the pack without TFC Aurora and it runs smoothly 

> you can update the TFC Aurora mod, this is the likely source, using newest version things should improve
